# Generated by Django 4.1.3 on 2022-11-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(max_length=15, verbose_name='Cedula del Paciente')),
                ('first_lastname', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('second_lastname', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('first_name', models.CharField(max_length=20, verbose_name='Primer Nombre')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Segundo Nombre')),
                ('date_of_birth', models.DateField(max_length=30, verbose_name='Fecha de Nacimiento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['patient_id'],
            },
        ),
    ]
