# Generated by Django 4.1.3 on 2022-11-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(verbose_name='Cedula del Paciente'),
        ),
    ]
