# Generated by Django 4.1.3 on 2022-11-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_patient_id_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
