# Generated by Django 4.1.3 on 2022-11-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=30, verbose_name='Segundo Nombre'),
        ),
    ]
