# Generated by Django 4.1.3 on 2022-11-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_patient_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='first',
        ),
    ]
